# Generated by Django 5.0.3 on 2024-03-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='augment',
            name='augment_effect',
        ),
        migrations.AddField(
            model_name='augment',
            name='augment_tier',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('prizm', 'Prizm')], default='silver', max_length=50),
        ),
    ]
