# Generated by Django 5.0.3 on 2024-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0002_remove_augment_augment_effect_augment_augment_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='augment_tier',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('prism', 'Prism')], default='silver', max_length=50),
        ),
    ]
