# Generated by Django 5.0.3 on 2024-03-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0008_remove_champion_job_remove_champion_origin_and_more'),
        ('medias', '0003_alter_photo_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champion_photo', to='champions.champion'),
        ),
    ]
