# Generated by Django 5.0.3 on 2024-03-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0003_alter_augment_augment_tier'),
        ('items', '0001_initial'),
        ('medias', '0004_alter_photo_champion'),
        ('synergies', '0002_alter_job_name_alter_origin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='augment_photo', to='augments.augment'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_photo', to='items.item'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_photo', to='synergies.job'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_photo', to='synergies.origin'),
        ),
    ]
