# Generated by Django 5.0.3 on 2024-03-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='챔피언', max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField()),
                ('AD', models.PositiveIntegerField()),
                ('DPS', models.PositiveIntegerField()),
                ('attack_range', models.PositiveIntegerField()),
                ('attck_speed', models.PositiveIntegerField()),
                ('armor', models.PositiveIntegerField()),
                ('magic_resistance', models.PositiveIntegerField()),
                ('skill_name', models.CharField(default='스킬 이름', max_length=100)),
                ('skill_category', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], max_length=50)),
                ('mana_start', models.IntegerField()),
                ('mana_total', models.IntegerField()),
                ('skill_description', models.TextField(default='스킬 설명')),
                ('skill_effect', models.TextField(default='스킬 효과')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
