# Generated by Django 5.0.3 on 2024-03-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='job',
            field=models.CharField(default='직업', max_length=50),
        ),
        migrations.AddField(
            model_name='champion',
            name='origin',
            field=models.CharField(default='계열', max_length=50),
        ),
    ]
