# Generated by Django 5.0.3 on 2024-03-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_remove_champion_dps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='attck_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='skill_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='skill_effect',
            field=models.TextField(),
        ),
    ]
