# Generated by Django 5.0.3 on 2024-03-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0004_alter_champion_attck_speed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='attck_speed',
            new_name='attack_speed',
        ),
    ]
