# Generated by Django 5.0.3 on 2024-03-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0005_rename_attck_speed_champion_attack_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='updated_at',
        ),
    ]
