# Generated by Django 5.0.3 on 2024-03-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0006_remove_champion_created_at_and_more'),
        ('synergies', '0002_alter_job_name_alter_origin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='synergies.job'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='synergies.origin'),
        ),
    ]
