# Generated by Django 5.0.3 on 2024-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0007_alter_champion_job_alter_champion_origin'),
        ('synergies', '0002_alter_job_name_alter_origin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='job',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='origin',
        ),
        migrations.AddField(
            model_name='champion',
            name='job',
            field=models.ManyToManyField(related_name='champions', to='synergies.job'),
        ),
        migrations.AddField(
            model_name='champion',
            name='origin',
            field=models.ManyToManyField(related_name='champions', to='synergies.origin'),
        ),
    ]
